---
title: Shafalovich K. S.
format: html
editor: visual
---

В датасете содержатся следующие переменные:

ID: уникальный ID на основе адреса дома; City: город; City_Size: размер города: большой или маленький; City_Region: город находится на севере или на юге; Street: на какой улице находится дом; Size_SquaredMeters: площадь дома; Price: цена; Sold: продан ли дом.

```{r}
                                                                   #Описательные статистики
#Рассчитайте следующие описательные статистики для цены домов: среднее, медиана, стандартное отклонение, минимум и максимум.
```

```{r}

```

```{r}
# Загрузка библиотеки для работы с данными
library(dplyr)
library(readr)
library(ggplot2)
library(stats)
library(lmtest)
```

```{r}
# Загрузка данных
data <- read.csv("house_sales_dataset.csv")
```

```{r}
# Проверка наличия пропущенных значений в таблице
missing_values <- is.na(data)

# Вывод количества пропущенных значений по каждому столбцу
colSums(missing_values)
```

```{r}
# Преобразуем, важные для анализа переменные, в класс factor.
data$City <- as.factor(data$City)
data$City_Size <- as.factor(data$City_Size)
data$City_Region <- as.factor(data$City_Region)
```

```{r}
str(data)
```

```{r}
# Рассчет описательных статистик для цен домов
price_stats <- data %>%
  summarise(
    mean_price = mean(Price),
    median_price = median(Price),
    sd_price = sd(Price),
    min_price = min(Price),
    max_price = max(Price)
  )

# Вывод описательных статистик
print(price_stats)
```

```{r}
                                #Проверка гипотез
#t-test. Сделайте сабсет, в котором будут только данные из Флоренции (Florence) и Неаполя (Naples). Следующее задание нужно выполнить на этом сабсете. C помощью t-теста, проверьте гипотезу о том, что цена отличается в зависимости от города, где расположен дом. Убедитесь, что переменная Цена распределена нормально. Проинтерпретируйте результаты t-теста. Постройте боксплот распределения цены для каждого города.
```

```{r}
# Создание сабсета с данными из Флоренции и Неаполя.
subset_data <- data %>%
  filter(City %in% c("Florence", "Naples"))

# Проверка нормальности распределения переменной Price (Цена).
shapiro.test(subset_data$Price)

# T-тест для сравнения цен в разных городах.
t_test_result <- t.test(Price ~ City, data = subset_data)

# Вывод результатов т-теста.
print(t_test_result)

# Построение боксплота распределения цены для каждого города.
ggplot(subset_data, aes(x = City, y = Price)) +
  geom_boxplot() +
  labs(title = "Распределение цен по городам",
       x = "Город",
       y = "Цена")
```

```{r}
#                       Тест нормальности Шапиро-Уилка

# Мы получили значение статистики W равное 0.982,  p-value равно 0.7873.
# Нулевая гипотеза в этом тесте заключается в том, что данные распределены нормально
# Высокое значение p-value (0.7873) указывает на то, что нет значимых доказательств против нулевой гипотезы, что данные распределены нормально.
# Таким образом, можно считать, что переменная "Price" имеет нормальное распределение
```

```{r}
#                                                              t-тест Уэлча

# Мы получили начение t-статистики равное -0.053004,  p-value равно 0.958.
# H0 в этом тесте заключается в том, что средние значения цен на дома в городах Флоренции и Неаполя равны.
# Поскольку значение p-value (0.958) больше общепринятого уровня значимости 0.05, нет достаточных доказательств для отвержения нулевой гипотезы.
#Это означает, что нет статистически значимых различий в ценах на дома между городами Флоренцией и Неаполем.
```

```{r}
# На графике боксплот мы наблюдаем выброс. Попробуем избавиться от него и посмотреть как изменятся результаты.
```

```{r}

# Находим индексы строк с городом Florence
florence_indexes <- which(data$City == "Florence")

# Находим индекс строки с минимальной ценой в городе Florence
min_price_florence_index <- florence_indexes[which.min(data$Price[florence_indexes])]

# Удаляем наблюдение с минимальной ценой в городе Florence
data_clean <- data[-min_price_florence_index, ]
```

```{r}
# Тест нормальности распределения цены для города Florence
shapiro_test_florence <- shapiro.test(data_clean$Price[data_clean$City == "Florence"])
print("Shapiro-Wilk normality test for Florence:")
print(shapiro_test_florence)

# Тест нормальности распределения цены для города Naples
shapiro_test_naples <- shapiro.test(data_clean$Price[data_clean$City == "Naples"])
print("Shapiro-Wilk normality test for Naples:")
print(shapiro_test_naples)

# Выполнение t-теста для сравнения цен в городах Florence и Naples
t_test_result <- t.test(Price ~ City, data = data_clean[data_clean$City %in% c("Florence", "Naples"), ])
print("Welch Two Sample t-test:")
print(t_test_result)

# Построение боксплотов распределения цены для каждого города
ggplot(data_clean[data_clean$City %in% c("Florence", "Naples"), ], aes(x = City, y = Price)) +
  geom_boxplot() +
  labs(title = "Распределение цен по городам",
       x = "Город",
       y = "Цена")
```

```{r}
# Показатели остались приблизительно такими же, поэтому на основе проведенного анализа можно также сделать вывод, что нет статистически значимых различий в ценах на дома между городами Florence и Naples (этот выброс можно было и не удалять).
```

```{r}
#                   Анализ категориальных переменных. 
# На этом же сабсете определите, если ли связь между городом и тем, куплен ли дом с помощью критерия Хи-квадрат Пирсона. Проинтерпретируйте результаты теста.
```

```{r}
# строим таблицу сопряженности
conf_table <- table(data$City, data$Sold)

# проводим тест х-квадрат Пирсона
chisq.test(conf_table)
```

```{r}
# Значение статистики X-squared равно 12.398, а число степеней свободы (df) равно 11, p-value составляет 0.3345.
#Таким образом, у нас нет достаточных доказательств для отвержения нулевой гипотезы о том, что нет связи между городом и фактом покупки дома, на уровне значимости 0.05. Это означает, что нет статистически значимой связи между местоположением дома (городом) и тем, был ли дом продан или нет в городах Флоренция и Неаполь.

```

```{r}
#                                   Регрессионный анализ
# Переходим к датасету со всеми городами. Представьте, что вам необходимо сделать регрессионный анализ, чтобы проверить, является ли размер города и площадь дома значимыми предикторами цены дома. Постройте модель, проверяющую эффект размера города и площади дома, а также их взаимодействие. Учитывайте, что в датасете несколько измерений в одном и том же городе. Проинтерпретируйте результаты модели. Проверьте требования нормального распределения остатков, гомоскедастичности, а также линейности взаимосвязи между ценой и площадью дома.


```

```{r}
# Регрессионный анализ
model <- lm(Price ~ Size_SquaredMeters * City_Size, data = data)

# Выводим сводку по модели
summary(model)

# Проверяем требования нормального распределения остатков
shapiro.test(residuals(model))

# Проверяем гомоскедастичность
bptest(model)

# Проверяем линейность взаимосвязи между ценой и площадью дома
plot(model)
```

```{r}

# Коэффициенты Intercept, Size_SquaredMeters и City_SizeSmall являются статистически значимыми (p-value < 0.05), что указывает на их влияние на цену дома.
# Взаимодействие между Size_SquaredMeters и City_Size не является статистически значимым (p-value > 0.05).
# Intercept оценивает базовый уровень цены дома при отсутствии других факторов.
# Коэффициент Size_SquaredMeters указывает нам на то, что каждый дополнительный квадратный метр площади дома в среднем увеличивает цену на 945.50 единиц.
# Коэффициент City_SizeSmall (-197412,92) указывает на снижение цены на дом в небольших городах по сравнению с большими городами.
# Взаимодействие между Size_SquaredMeters и City_SizeSmall не имеет статистически значимого влияния на цену дома.
# Множественный R-квадрат (Multiple R-squared) равен 0.4624, что означает, что примерно 45.86% вариации в цене дома объясняется выбранными независимыми переменными.
# Скорректированный R-квадрат (Adjusted R-squared) равен 0.4624 что также учитывает количество независимых переменных.
# Тест Шапиро-Уилка для остатков (p-value = 5.183e-05) указывает на отклонение остатков от нормального распределения.
# Тест Бройша-Пагана для гомоскедастичности остатков (p-value = 0.9508) не позволяет отвергнуть нулевую гипотезу, что остатки гомоскедастичны.
```

```{r}
# Воспользуемся еще тестом Колмогорова-Смирнова на нормальность распределения остатков
ks.test(residuals(model), "pnorm", mean = mean(residuals(model)), sd = sd(residuals(model)))

```

```{r}
# P-значение составляет 0.1663, что означает, что нет статистически значимых доказательств против того, что остатки следуют нормальному распределению.
```

```{r}
#                                                                      Визуализация данных
#С помощью библиотеки ggplot2 постройте диаграмму рассеяния, отражающую взаимосвязь площади дома и цены. Цветом отметьте размер города. Добавьте к графику название, подпишите оси и легенду.

```

```{r}

# Создание графика
scatter_plot <- ggplot(data, aes(x = Size_SquaredMeters, y = Price, color = City_Size)) +
  geom_point() +  # Добавление точек
  labs(title = "Зависимость цены дома от площади",
       x = "Площадь дома (кв. м)",
       y = "Цена дома",
       color = "Размер города") +  # Название осей и легенды
  theme_minimal()  # Стиль графика

# Вывод графика
print(scatter_plot)
```
